### ISSUE TITLE
TODO-LIST

### ISSUE THREAD

**Issue by ArakiTakaki** [ArakiTakaki/react-creator#1]
# 基本機能の作成

- [ ] 初期化設定を追加
    - HASH
    - [ ] Document
- [ ] component作成機能を追加
    - HASH
    - [ ] Document
- [ ] storeのactions追加機能を作成
    - HASH
    - [ ] Document
- [ ] componentの削除機能を追加
    - HASH
    - [ ] Document

**Comment by ArakiTakaki** [comment]
バグ報告
- [ ] /src/js/store/configreStore.js
    - 13:3  error  'reducers' is not defined  no-undef
    - reducersのimportし忘れ
- [ ] /src/js/store/state.js
    -  3:7  error  Insert `·`  prettier/prettier
    - Object形式がlinterで弾かれる事案
- [ ] Module not found: Error: Can't resolve './containers/Root' in '/src/js'
    - import Root from "./container/Root"; -> containersの間違い
- [ ] actions.js
    - incrementが二つある（片方はdecrement）
- [ ] reducers.js
    -       return { ...state, num: stat.num++ }; -> statじゃなくてstate
- [ ] index.js -> import "../sass/base.sass";
- [ ] base.sass typo -> @import "valiables"
